[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
# enableCORS is overridden to true by Streamlit when XsrfProtection is true
enableXsrfProtection = true 

[client]
showSidebarNavigation = true